service: sf-request-svg-difference
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

